header:
  version: 17

machine: qemux86-64
distro: poky
target:
  - core-image-base

defaults:
  repos:
    branch: kirkstone

repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  
  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    layers:
      meta-oe:
      meta-python:
      meta-networking:

local_conf_header:
  meta-custom: |
    IMAGE_INSTALL:append = " util-linux-sfdisk openssh bash e2fsprogs"
    KERNEL_FEATURES:append = " features/overlayfs/overlayfs.scc"