parent = "core/debian-bookworm"

recipes = [
    # Set a static hostname.
    "core/set-hostname",
    # Persist `/root`.
    "core/persist-root-home",
    # Setup and enable SSH.
    "core/ssh",
    # Setup the network.
    "setup-network",
    # Enable discovery of the system in the local network.
    "rugpi-extra/avahi",
    # Install a static website.
    "hello-world",
]

[parameters."core/set-hostname"]
hostname = "rugix-template"

[parameters."core/ssh"]
root_authorized_keys = """
<INSERT YOUR PUBLIC SSH KEY HERE>
"""
